# Generated by Django 3.2.4 on 2021-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_produit',
            field=models.ImageField(upload_to=''),
        ),
    ]
